-- dependency/Services.lua
do
    local RbxService = {
        -- Server:
        AssetService             = game:GetService("AssetService"),
        BadgeService             = game:GetService("BadgeService"),
        DataStoreService         = game:GetService("DataStoreService"),
        FriendService            = game:GetService("FriendService"),
        GamePassService          = game:GetService("GamePassService"),
        GroupService             = game:GetService("GroupService"),
        HttpService              = game:GetService("HttpService"),
        InsertService            = game:GetService("InsertService"),
        MessagingService         = game:GetService("MessagingService"),
        PermissionsService       = game:GetService("PermissionsService"),
        PolicyService            = game:GetService("PolicyService"),
        ServerScriptService      = game:GetService("ServerScriptService"),
        ServerStorage            = game:GetService("ServerStorage"),
        TeleportService          = game:GetService("TeleportService"),
        -- Client:
        ContextActionService     = game:GetService("ContextActionService"),
        CoreGui                  = game:GetService("CoreGui"),
        GuiService               = game:GetService("GuiService"),
        HapticService            = game:GetService("HapticService"),
        NotificationService      = game:GetService("NotificationService"),
        TouchInputService        = game:GetService("TouchInputService"),
        UserInputService         = game:GetService("UserInputService"),
        VRService                = game:GetService("VRService"),
        VirtualUser              = game:GetService("VirtualUser"),
        -- Cross Platform:
        Chat                     = game:GetService("Chat"),
        CollectionService        = game:GetService("CollectionService"),
        ContentProvider          = game:GetService("ContentProvider"),
        Debris                   = game:GetService("Debris"),
        Lighting                 = game:GetService("Lighting"),
        LocalizationService      = game:GetService("LocalizationService"),
        LogService               = game:GetService("LogService"),
        MarketplaceService       = game:GetService("MarketplaceService"),
        PathfindingService       = game:GetService("PathfindingService"),
        PhysicsService           = game:GetService("PhysicsService"),
        Players                  = game:GetService("Players"),
        ReplicatedFirst          = game:GetService("ReplicatedFirst"),
        ReplicatedStorage        = game:GetService("ReplicatedStorage"),
        RunService               = game:GetService("RunService"),
        ScriptContext            = game:GetService("ScriptContext"),
        Selection                = game:GetService("Selection"),
        SoundService             = game:GetService("SoundService"),
        StarterGui               = game:GetService("StarterGui"),
        StarterPack              = game:GetService("StarterPack"),
        StarterPlayer            = game:GetService("StarterPlayer"),
        Stats                    = game:GetService("Stats"),
        Teams                    = game:GetService("Teams"),
        TestService              = game:GetService("TestService"),
        TextService              = game:GetService("TextService"),
        TweenService             = game:GetService("TweenService"),
        Workspace                = game:GetService("Workspace"),
        -- Hidden:
        AdService                = game:GetService("AdService"),
        AnalyticsService         = game:GetService("AnalyticsService"),
        AssetCounterService      = game:GetService("AssetCounterService"),
        CookiesService           = game:GetService("CookiesService"),
        DebuggerManager          = game:GetService("DebuggerManager"),
        Geometry                 = game:GetService("Geometry"),
        HSRDataContentProvider   = game:GetService("HSRDataContentProvider"),
        HttpRbxApiService        = game:GetService("HttpRbxApiService"),
        JointsService            = game:GetService("JointsService"),
        MemStorageService        = game:GetService("MemStorageService"),
        MeshContentProvider      = game:GetService("MeshContentProvider"),
        ProcessInstancePhysicsService = game:GetService("ProcessInstancePhysicsService"),
        VirtualInputManager      = game:GetService("VirtualInputManager"),
        Visit                    = game:GetService("Visit"),
        -- Deprecated:
        TextChatService          = game:GetService("TextChatService"),
        PointsService            = game:GetService("PointsService"),
    }
    return RbxService
end
